In [1]:
import cv2
import numpy as np
import tensorflow as tf

In [2]:
# Load the pre-trained MobileNet model
model = tf.keras.applications.MobileNetV2(weights='imagenet')



14536120/14536120 [==============================] - 17s 1us/step


In [3]:
# Load the image
image = cv2.imread('stethoscope.jpg')

# Preprocess the image
resized_image = cv2.resize(image, (224, 224))
print(resized_image)
input_image = tf.keras.applications.mobilenet.preprocess_input(resized_image)

[[[188 182 183]
  [184 178 179]
  [185 180 181]
  ...
  [101 101 101]
  [100 100 100]
  [101 101 101]]

 [[182 177 178]
  [179 173 174]
  [180 175 176]
  ...
  [101 101 101]
  [100 100 100]
  [101 101 101]]

 [[180 174 175]
  [176 170 171]
  [178 173 174]
  ...
  [102 102 102]
  [101 101 101]
  [102 102 102]]

 ...

 [[243 237 238]
  [239 233 234]
  [240 235 236]
  ...
  [239 237 237]
  [239 237 237]
  [244 242 242]]

 [[238 232 233]
  [239 233 234]
  [238 232 233]
  ...
  [240 238 238]
  [240 238 238]
  [247 245 245]]

 [[243 237 238]
  [244 238 238]
  [242 237 238]
  ...
  [244 242 242]
  [244 242 242]
  [248 246 246]]]


In [4]:
# Add batch dimension
input_image = np.expand_dims(input_image, axis=0)

# Perform object recognition
predictions = model.predict(input_image)

1/1 [==============================] - 6s 6s/step


In [5]:
# Get the top 5 predicted classes and their probabilities
top_predictions = tf.keras.applications.mobilenet.decode_predictions(predictions, top=5)[0]


35363/35363 [==============================] - 0s 2us/step


In [10]:
# Set a probability threshold
probability_threshold = 0.8

# Display the top predictions
for pred in top_predictions:
    class_name = pred[1]
    probability = pred[2]
    print(f"Class: {class_name}, Probability: {probability}")

# Display the image
cv2.imshow('Object Recognition', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Class: stethoscope, Probability: 0.9979115128517151
Class: whistle, Probability: 0.00014759894111193717
Class: hook, Probability: 0.00010828517406480387
Class: loupe, Probability: 7.866165833547711e-05
Class: sunglasses, Probability: 6.668024434475228e-05
