In [1]:
import cv2
import numpy as np
import tensorflow as tf

In [2]:
# Load the pre-trained MobileNet model
model = tf.keras.applications.MobileNetV2(weights='imagenet')



14536120/14536120 [==============================] - 25s 2us/step


In [3]:
# Load the image
image = cv2.imread('dataset/object.jpg')

# Preprocess the image
resized_image = cv2.resize(image, (224, 224))
print(resized_image)
input_image = tf.keras.applications.mobilenet.preprocess_input(resized_image)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [4]:
# Add batch dimension
input_image = np.expand_dims(input_image, axis=0)

# Perform object recognition
predictions = model.predict(input_image)

1/1 [==============================] - 2s 2s/step


In [5]:
# Get the top 5 predicted classes and their probabilities
top_predictions = tf.keras.applications.mobilenet.decode_predictions(predictions, top=5)[0]


35363/35363 [==============================] - 0s 3us/step


In [ ]:
# Display the top predictions
for pred in top_predictions:
    class_name = pred[1]
    probability = pred[2]
    print(f"Class: {class_name}, Probability: {probability}")

# Display the image
cv2.imshow('Object Recognition', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Class: folding_chair, Probability: 0.31155693531036377
Class: rocking_chair, Probability: 0.08330704271793365
Class: dining_table, Probability: 0.057280655950307846
Class: desk, Probability: 0.01616540551185608
Class: hook, Probability: 0.008895990438759327
